### ISSUE TITLE
How did you setup the random server picker?

### ISSUE THREAD

**Issue by Marcus624** [tomo54321/McServer-List#1]
Hi really liked your code! I was wondering how did you setup the subdomain and the web socket for the random server picker?

**Comment by tomo54321** [comment]
> Hi really liked your code! I was wondering how did you setup the subdomain and the web socket for the random server picker?

Hey! Thanks for the feedback! It looks like I hadn't made the proxy repo public, you can now find it [here](https://github.com/tomo54321/mcserver-list-proxy). I haven't worked on the project for a while, but if I recall I could never get it to work with the player joining the server (though I maybe wrong so feel free to give it a go!)

The proxy repo I created is an adaptation of [this repo](https://github.com/janispritzkau/minecraft-reverse-proxy) so there maybe some help with the server proxy here.

I hope this helps :)
