### ISSUE TITLE
Hi need some help, images seem broken.

### ISSUE THREAD

**Issue by GreenArrowlol** [tomo54321/McServer-List#5]
Images seem broken
![image](https://github.com/user-attachments/assets/e87c9bc2-e3ed-4f24-94a1-a4e34be5cef4)
![image](https://github.com/user-attachments/assets/d6156dbc-b673-4e11-9a9c-58c7cf9e8405)

I tried uploading a gif from https://auto.creavite.co/animated-banners

**Comment by tomo54321** [comment]
Hey!

Make sure that you've ran `php artisan storage:link` in the mcserver-list folder and that should fix your issue! :)
