### ISSUE TITLE
How to remove random server from the header?

### ISSUE THREAD

**Issue by GreenArrowlol** [tomo54321/McServer-List#6]
I want to completely remove it as I think it isn't working. Do let me know how to remove it.

**Comment by tomo54321** [comment]
Hi,

You are correct that the random server wouldn't be working unless you have setup the random server's server, which can be found here: https://github.com/tomo54321/mcserver-list-proxy which is intended to pick a server at random, display it on the website then allow users to connect to the same server in Minecraft using a single IP that changes the server on refresh. Though this is unfinished and buggy.

If you'd like to remove the random server from the header, you just need to remove the following line: https://github.com/tomo54321/McServer-List/blob/master/routes/web.php#L17
