### ISSUE TITLE
ErrorException page coming when updating a server list

### ISSUE THREAD

**Issue by GreenArrowlol** [tomo54321/McServer-List#7]
![image](https://github.com/user-attachments/assets/69a059da-9697-42dd-8c31-dab28319a80e)

Happens as soon as we update a server in the list.

**Comment by tomo54321** [comment]
Hi,

This is just because banner jpg path file doesn't exist, either it has been removed manually or it was never uploaded. You're going to need to implement a check that the file exists which is an oversight on my behalf as it is only checking if the path exists in the database.

**Comment by GreenArrowlol** [comment]
> Hi,
> 
> This is just because banner jpg path file doesn't exist, either it has been removed manually or it was never uploaded. You're going to need to implement a check that the file exists which is an oversight on my behalf as it is only checking if the path exists in the database.

Are you able to resolve it? I do not have experience with laravel and such.

**Comment by GreenArrowlol** [comment]
I was able to record another issue.

So first I checked remove banner and clicked save and some issue came so I went back to add another banner and now this happens
https://hrzn.pics/sF0Zqy42YU

facing same issue while deleting too.

Conclusion: if we manually remove banner it breaks the whole server by not letting us add a new banner or delete the server.

If we leave that alone it doesn't do anything.

One solution would be for this to remove the checkbox.

**Comment by GreenArrowlol** [comment]
Temp solution is to hide it
![image](https://github.com/user-attachments/assets/64ce64ce-7605-44f9-b0d9-3b1a52fbd6ec)

this is the directory
![image](https://github.com/user-attachments/assets/46c39d0d-c5c1-43ea-a2a5-dff3375d43cf)


Let me know how to wipe this server from the list as because of what happened earlier I'm unable to do anything with this
https://corenode.top/server/1

**Comment by tomo54321** [comment]
Being a quick fix, I can resolve it for you. Looking at the video you've sent over, it appears that this is a permissions issue.

**Comment by tomo54321** [comment]
I have just merged in changes for this, feel free to pull the repo again :)

**Comment by GreenArrowlol** [comment]
Great thanks.
